### ISSUE TITLE
Feature request: support for Manjaro

### ISSUE THREAD

**Issue by JohnBlood** [Rizwan-Hasan/ArchLinux-Mirrorlist-Manager#2]
Unlike most distros based on Arch, Manjaro has it's repositories and mirrors. When I tested your app, it replaced my Manjaro mirrors with Arch mirrors. I was able to reset my mirrors.

Please add support/detection for non-Arch mirrors, especially Manjaro.

**Comment by Rizwan-Hasan** [comment]
Thanks for letting me know. I am currently working on it. Next version will have manjaro detection but it won't support manjaro mirrors. So, it will exit after showing warning and I will also update documentation for encouraging not to try Mirrorlist Manager with manjaro.
