### ISSUE TITLE
Documentation required

### ISSUE THREAD

**Issue by Spixmaster** [Rizwan-Hasan/ArchLinux-Mirrorlist-Manager#7]
Hello there,
I really appreciate this software but it is not easy to understand which is a huge downside. What is the meaning of the button "No of Sever"/"2"... And what does generate do? Its meaning cannot be concluded from the behaviour. Despite that it works great!

Regards
Spixmaster

**Comment by Rizwan-Hasan** [comment]
**Hi Spixmaster**, Glad to know that you're appreciating my little effort in making this software. Sorry for the trouble you've faced using the software. I'll try to provide the documentation soon. But it will be also very helpful for me and all the users if you wish to contribute to the project by writing the documentation. **Thanks!** 
Now let me clear your confusion. The "Generate" button will create a mirrorlist of the selected country with including all the servers available for that country and the "No of Sever" is used to provide a hint to the "Rankmirrors" script that how many servers user wished to have in mirrorlist after sorting all the servers from existing mirrorlist by their speed.

**Comment by Rizwan-Hasan** [comment]
#### **Hi Spixmaster**, 
Glad to know that you're appreciating my little effort of making this software. You can give this project a **star** as an appreciation also 😉. Sorry for the trouble you've faced using the software 😥. I'll try to provide the documentation soon. But it will be also very helpful for me and all the users if you wish to contribute to the project by writing the documentation 😇. **Thanks!** 😊
<br />Now let me clear your confusion. The _**"Generate"**_ button will create a mirrorlist of the selected country with including all the servers available for that country and the **_"No of Sever"_** is used to provide a hint to the _**"Rankmirrors"**_ script that how many servers user wished to have in mirrorlist after sorting all the servers from existing mirrorlist by their speed. 😃

**Comment by Spixmaster** [comment]
With documentation, I mean a short description in the software itself because especially that left button "No of Server" is not intuitive. The default confuses a lot because why should someone choose not a single server of the ranked mirror servers?!
Either way, I thank you for that super fast reply.

**Comment by Rizwan-Hasan** [comment]
**You're most welcome** :blush:
